### ISSUE TITLE
Gist id feature not working?

### ISSUE THREAD

**Issue by finestructure** [SwiftFiddle/swiftfiddle-web#404]
I saw that help states

> Append a GitHub gist ID to the URL
(e.g. swiftfiddle.com/<gist_id_goes_here>)

I've tried this with this gist: https://gist.github.com/finestructure/742260260c633c3ec62004f009507306 with various ways of appending the gist id (both just the id as well as finestructure/id) but can't seem to get it right 😅

Should this be working or is this not available anymore?

**Comment by kishikawakatsumi** [comment]
Thank you for reporting. 

The structure of the response returned by the Gist API was incorrect. I assumed that the `language` property could not be null. I fixed it and deployed. It now works correctly. Thanks.

https://github.com/SwiftFiddle/swiftfiddle-web/commit/837b18ce768cf250c38c43d362e299a40822241c
