### ISSUE TITLE
Is it possible to wait for async code to complete?

### ISSUE THREAD

**Issue by michaelalhilly** [SwiftFiddle/swiftfiddle-web#448]
Hi. I'm trying to test async procedures. Here's what I'm working with:

```
import Foundation

let plusOneError = NSError(
  domain: "addOne",
  code: 10,
  userInfo: [
      NSLocalizedDescriptionKey: "Plus one error."
  ])

func addOne(_ value: Int, delay: Double = 0.0) async throws -> Void {
  try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
        DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
            if value < 0 { continuation.resume(throwing: plusOneError) }
            print(value + 1)
            continuation.resume(returning: Void())
        }
    }
}

func startProcess() -> Void {

  let group = DispatchGroup()
  group.enter()

  Task {
    do {

      try await addOne(5, delay: 1.0)
      group.leave()

    } catch {
      print(error)
      group.leave()
    }
  }

  group.wait()
}

startProcess()
```

**Comment by kishikawakatsumi** [comment]
@michaelalhilly 

This code waits in the main thread in `group.wait()` at line 37. Then it dispatches the procedure on the main thread at line 12. However, the main thread is already waiting, so the main thread does not run anymore. This is a state called deadlock. To solve this problem, for example, change `DispatchQueue.main` in line 12 to `DispatchQueue.global()` to execute the procedure in a different thread.

**Comment by michaelalhilly** [comment]
@kishikawakatsumi Thank so much! Just getting into concurrency with swift and that helps.
