### ISSUE TITLE
Share window does not appear

### ISSUE THREAD

**Issue by wlybe** [SwiftFiddle/swiftfiddle-web#458]
Hi,

When I try to share a code snipper, the share windows appears very briefly and then disappears. After that, this error appears

> TypeError: Cannot set properties of null (setting 'href')

Thanks for providing this cool tool :)

**Comment by kishikawakatsumi** [comment]
Fixed by https://github.com/SwiftFiddle/swiftfiddle-web/commit/6ce65813599ba83ba0d42a07a053d302e3b78897

Can you test it?

**Comment by wlybe** [comment]
Indeed it works.
Thanks for the quick fix 👍
