### ISSUE TITLE
incorrect Swift version when choosing nightly-5.7

### ISSUE THREAD

**Issue by HassanTaleb90** [SwiftFiddle/swiftfiddle-web#517]
When we choose Swift Version: nightly-5.7 , the output is for: Swift version 5.7.1
expected: Swift version 5.7

output example:
Swift version 5.7.1-dev (LLVM 597c04db307f4ed, Swift 2e814ca5d704c9f)
Target: x86_64-unknown-linux-gnu
Hello, World!
Hello, Swift!

**Comment by kishikawakatsumi** [comment]
It is expected behavior. nightly-5.7 docker image now returns the version string. This string is not output on my end.
