### ISSUE TITLE
How to copy code on iOS?

### ISSUE THREAD

**Issue by tammofreese** [SwiftFiddle/swiftfiddle-web#523]
Today I was AFK, but needed to try out some Swift code for a StackOverflow answer. I used my iPhone and SwiftFiddle worked beautifully. 🚀 

I could not find a simple way to copy the code I typed in though. I took the scenic route (screenshot, extract code via OCR). Is there a better way that I missed? If not, I would love a “Copy to Clipboard” button :)

**Comment by kishikawakatsumi** [comment]
A long press and release on the cursor location will bring up a context menu that includes copy and paste.

<img src="https://user-images.githubusercontent.com/40610/210547736-324e33e3-0069-43e0-828f-e2f97c96f30f.png" width=320 />

**Comment by tammofreese** [comment]
Thanks! If I would like to select the whole code, how can I do that? I figured out I can select single words with a double tap, but found no way to select all.

**Comment by tammofreese** [comment]
… found it, via Command Palette > Expand Selection! Thanks!
