### ISSUE TITLE
Support Swift V5.7.2 and V5.7.3

### ISSUE THREAD

**Issue by HassanTaleb90** [SwiftFiddle/swiftfiddle-web#527]
There is a new versions of Swift: 5.7.2 and 5.7.3
https://github.com/apple/swift/releases/tag/swift-5.7.2-RELEASE
https://github.com/apple/swift/releases/tag/swift-5.7.3-RELEASE
 Can you support please?

**Comment by kishikawakatsumi** [comment]
Released

**Comment by HassanTaleb90** [comment]
Thanks! But there is two bugs:
1- v 5.7.3 does not execute
2- all other versions are now too slow!

[image](https://user-images.githubusercontent.com/49780321/215077180-0edfd8b3-7364-4e82-b1b2-f8ed00a1f83a.jpeg)![image](https://user-images.githubusercontent.com/49780321/215077202-b288b478-8885-48bd-8454-59ccf7d89c31.jpeg)![image](https://user-images.githubusercontent.com/49780321/215077220-aadeb4b8-1797-4919-9fd7-b2cf7018cafd.jpeg)
