### ISSUE TITLE
UX issue - share button tries to walk off the screen

### ISSUE THREAD

**Issue by heckj** [SwiftFiddle/swiftfiddle-web#592]
I was exploring SwiftFiddle, which is tremendous, and while doing so noticed a minor bug.

When you mouse over back and forth between the button `LSP` and the button `Share`, the position of the Share button migrates just slightly to the right. I made a short video illustrating what I'm seeing. I didn't see a version or reference to provide you specific release detail, but this was happening on 5 may, 2023 15:13 UTC

https://user-images.githubusercontent.com/43388/236498095-8da8f045-e4c3-4b0c-aaba-549a054d0cf0.mov

**Comment by kishikawakatsumi** [comment]
Thanks for the report. And thanks for the donation! It seems to be a Safari-only problem. That's odd; I fixed it at https://github.com/SwiftFiddle/swiftfiddle-web/pull/593.
