### ISSUE TITLE
Laggy Editor

### ISSUE THREAD

**Issue by bbrk24** [SwiftFiddle/swiftfiddle-web#647]
SwiftFiddle has possibly the laggiest editor I've ever used. Even things like Ctrl-A (select all) are slow. I find it easier to write my code in Notepad, and then copy-paste it into the browser to test it.

I recently got a new computer and it hasn't been as bad there, so it might be hardware-related, but I don't understand how an in-browser editor can be unusable with a 10th gen i7 and then work fine on newer hardware. It isn't browser-specific; I've noticed the same behavior on both Firefox and Chrome.

**Comment by kishikawakatsumi** [comment]
@bbrk24 The perception of speed is subjective, so it is impossible to judge how slow it is based on your description. Can you write an objective description by recording the screen or measuring the time?

**Comment by bbrk24** [comment]
Sure. Here's what I did:

1. Delete everything in the editor
2. Wait for the LSP to finish initializing
3. Type the word "print"
4. Start the stopwatch
5. Once the `t` shows up in the editor, stop the stopwatch.

Here's the results:

| | Older Computer | Newer Computer |
|:--|:--|:--|
| CPU | i7-10750H | Ryzen 9 7940HS |
| OS | Windows 10 | Windows 11 |
| Time | **11.2 s** | too short to measure |

Both times were measured in Firefox 114. If I don't wait for the LSP to finish initializing, the lag is basically zero even on the older machine.

Eleven seconds to type five letters is unacceptably slow, imo. This isn't a problem with the older machine, either; vs code works fine.

**Comment by kishikawakatsumi** [comment]
Thank you. I understand what is happening. However, I can't reproduce it in my environment, so I can't fix it right away. Please let me know if you have any additional information on how I can reproduce it, or if others are experiencing similar problems.

**Comment by kishikawakatsumi** [comment]
However, it appears that perhaps the process of receiving LSP code completion is the bottleneck. I cannot fix it now due to a lack of time. However, I would like to improve that area when I have more time. Pull Requests are always welcome.

**Comment by HassanTaleb90** [comment]
> Thank you. I understand what is happening. However, I can't reproduce it in my environment, so I can't fix it right away. Please let me know if you have any additional information on how I can reproduce it, or if others are experiencing similar problems.

I'm having the same problem, I think it's related to LSP.

**Comment by bbrk24** [comment]
On the older computer it's gone from 11.2s to 10.3s. A bit faster, but not appreciably. The letters "pr" show up pretty much immediately, and then the next three take a few seconds each.
