### ISSUE TITLE
Swift 5.9 - run error

### ISSUE THREAD

**Issue by HassanTaleb90** [SwiftFiddle/swiftfiddle-web#692]
Sometimes when I press run, an error occurs.

<img width="1173" alt="Screenshot 2023-09-26 at 9 01 02 AM" src="https://github.com/SwiftFiddle/swiftfiddle-web/assets/49780321/f2b02924-eb1d-4f2d-8ace-beb6a0e02473">

**Comment by kishikawakatsumi** [comment]
SwiftFiddle is managed by Kubernetes. It is automatically restarted when a server down is detected.
