### ISSUE TITLE
Line and column numbers are wrong

### ISSUE THREAD

**Issue by HassanTaleb90** [SwiftFiddle/swiftfiddle-web#738]
code: `print(`
output: 2:1: error: expected expression in list of expressions
expected: 1:7: error: expected expression in list of expressions

**Comment by HassanTaleb90** [comment]
Oh, I see. I tested only on https://www.jdoodle.com/execute-swift-online/.
<img width="515" alt="Screenshot 2023-12-25 at 3 53 29 AM" src="https://github.com/SwiftFiddle/swiftfiddle-web/assets/49780321/0aa7280e-7a80-4d60-b456-ed3432e6d558">
It makes sense that the problem isn't in a line that doesn't exist yet.
How can we highlight errors if the line doesn't exist? 🤔 I think Xcode adds an extra line for that.
<img width="447" alt="Screenshot 2023-12-25 at 4 00 55 AM" src="https://github.com/SwiftFiddle/swiftfiddle-web/assets/49780321/40bc17c1-b59c-46e6-bed8-49f368779d03">

**Comment by kishikawakatsumi** [comment]
Yes, Parser tries to find the closing bracket to the end of the file, so it will give an error for a line number that does not exist.
After the error is printed, you can add a line corresponding to the line number in error, for example, to get the expected result.
