### ISSUE TITLE
There is a significant time gap between requests for different Swift versions.

### ISSUE THREAD

**Issue by HassanTaleb90** [SwiftFiddle/swiftfiddle-web#739]
Swift 5.1: (so fast)
<img width="686" alt="Screenshot 2023-12-25 at 4 27 17 AM" src="https://github.com/SwiftFiddle/swiftfiddle-web/assets/49780321/24e502bc-235a-4549-9750-32a9caa45803">

Swift 5.9.2 (so slow)
<img width="690" alt="Screenshot 2023-12-25 at 4 26 42 AM" src="https://github.com/SwiftFiddle/swiftfiddle-web/assets/49780321/f912ca4f-d49b-4f61-85e3-1a8ea3c9854a">

**Comment by kishikawakatsumi** [comment]
This is intended behavior. Some old versions running on Azure functions now.
