### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by HassanTaleb90** [SwiftFiddle/swiftfiddle-web#753]
Sometimes, when pressing "Run," this error occurred:

<img width="779" alt="Screenshot 2024-01-13 at 4 51 34 AM" src="https://github.com/SwiftFiddle/swiftfiddle-web/assets/49780321/0b4237b2-3364-459b-9dcd-218b68d0b0bf">

**Comment by kishikawakatsumi** [comment]
Does this problem still occur a lot these days? Was the server busy when you tried?
