### ISSUE TITLE
error: no such module 'SwiftUI'

### ISSUE THREAD

**Issue by Leggerla** [SwiftFiddle/swiftfiddle-web#764]
Hi!

I'm new to Swift and I was trying to use the playground to create an HStack using this code:

```
struct ContentView: View {
    
    var body: some View {
        
        HStack {
                        
            Text("Some Text")
            Text("Another Text")
            
        }
        
    }
    
}
```

When running, the error occurred "cannot find type 'View' in scope"
Then I added "import SwiftUI" to the top of the code and the error changed to "no such module 'SwiftUI'".

As far as I understand, "View" is one of the most basic things in Swift. Is there a way I can use it in your playground?

**Comment by kishikawakatsumi** [comment]
SwiftUI is not part of Swift, but a proprietary framework available only for Apple platforms (e.g. macOS, iOS, etc.) SwiftUI requires a Mac host to run. It is not practical to use a Mac to host web applications. Therefore, there is no SwiftUI framework in this environment, so this error is a reasonable result.

**Comment by Leggerla** [comment]
Got it, too bad :(
Thanks for the swift 😆 response
