### ISSUE TITLE
'docker: invalid reference format' when >= Nightly-5.7

### ISSUE THREAD

**Issue by stustill** [SwiftFiddle/swiftfiddle-web#774]
When running with the nightly releases, I get the following error message (example from `nightly-main`:

```
Swift version 5.11-dev (LLVM 6751d2aa5dca44c, Swift 90f192abfeb5f17)
Target: x86_64-unknown-linux-gnu
docker: invalid reference format.
See 'docker run --help'.
```

Impacting Runners:
 * `nightly-5.7`
 * `nightly-5.8`
 * `nightly-5.9`
 * `nightly-5.10`
 * `nightly-main`

**Comment by kishikawakatsumi** [comment]
@stustill Thank you for reporting. I've fixed that.
