### ISSUE TITLE
Run an asynchronous task

### ISSUE THREAD

**Issue by vBoykoGit** [SwiftFiddle/swiftfiddle-web#776]
Can I run an asynchronous task in swiftfiddle?
Nothing was printed with this code

```
import Foundation

let main = DispatchQueue.main

main.async {
    print("on main")
}
```

**Comment by kishikawakatsumi** [comment]
@vBoykoGit 

This is because the process is terminated before the asynchronous processing is executed.
Add the following code to wait for the main process not to terminate. Also, terminate the process so that it does not remain in a wait state after the asynchronous process has finished.

```swift
import Foundation

let main = DispatchQueue.main

main.async {
    print("on main")
    exit(0) // Terminate the process
}

RunLoop.main.run() // Wait async thread
```
