### ISSUE TITLE
Uncontrollable zooming when used with Android smartphone

### ISSUE THREAD

**Issue by krnntp** [SwiftFiddle/swiftfiddle-web#871]
Swiftfiddle is all but unusable from an Android smartphone, as typing into the code buffer causes the text to zoom to a ridiculously huge degree of magnification. The usual gestures – pinching and dragging, double-tapping the screen — do nothing to set size back to normal inside the vastly enlarged text input area. And since dragging the screen view from side to side or up and down does not work either, it is a very tedious task to reach the title bar or the console window, where the double-tap gesture works. An agonizing experience, which I'm sure you didn't intend.

**Comment by kishikawakatsumi** [comment]
The editor is monaco-editor. monaco-editor does not support mobile devices.

>  Is the editor supported in mobile browsers or mobile web app frameworks?
https://github.com/microsoft/monaco-editor
