### ISSUE TITLE
Cannot import swift-numerics' modules

### ISSUE THREAD

**Issue by kkebo** [SwiftFiddle/swiftfiddle-web#929]
## Steps to reproduce

Run the following code:

```swift
import Numerics
```

or

```swift
import RealModule
```

URL: https://swiftfiddle.com/l6d67jps5rb6njrr7275znej7q

## Expected behavior

The `Numerics` module will be successfully imported.

## Actual behaviors

- Swift 6.0
  - `error: no such module 'Numerics'`
- Swift 5.10.1
  - `error: missing required 0module '_NumericsShims'`
- Swift 5.9.2
  - `error: missing required 0module '_NumericsShims'`
- Swift 5.8.1
  - `error: missing required 0module '_NumericsShims'`

**Comment by kishikawakatsumi** [comment]
Thanks for the report. I was able to fix it by adding the following Import Path. Not all versions have been fixed, but we will update them as they become available.

```
-I . /swiftfiddle.com/_Packages/.build/checkouts/swift-numerics/Sources/_NumericsShims/include/
```

**Comment by kishikawakatsumi** [comment]
All environments had been fixed.

**Comment by kkebo** [comment]
Thank you so much!
